### ISSUE TITLE
Custom login gives TypeError in getAuthFetcher

### ISSUE THREAD

**Issue by Jmolenberghs** [solid/solid-node-client#10]
When I'm trying to use a custom login I get 
(node:36065) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Object.getAuthFetcher (/mnt/70D8F8E6D8F8AC0A/Documents/courses/stage/projects/nodeSolidAPI/node_modules/solid-auth-fetcher/dist/obtainAuthHeaders.js:11:29)
    at SolidNodeClient.<anonymous> (/mnt/70D8F8E6D8F8AC0A/Documents/courses/stage/projects/nodeSolidAPI/node_modules/solid-node-client/src/index.js:100:67)
    at step (/mnt/70D8F8E6D8F8AC0A/Documents/courses/stage/projects/nodeSolidAPI/node_modules/solid-node-client/src/index.js:33:23)
    at Object.next (/mnt/70D8F8E6D8F8AC0A/Documents/courses/stage/projects/nodeSolidAPI/node_modules/solid-node-client/src/index.js:14:53)
    at fulfilled (/mnt/70D8F8E6D8F8AC0A/Documents/courses/stage/projects/nodeSolidAPI/node_modules/solid-node-client/src/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Node.js

session = await client.login({
            idp: "https://inrupt.net",
            username: "<appropriateUserNme",
            password: "<appropriate password>",
            debug: true
        });

it used to work with solid-auth-cli

**Comment by jeff-zucker** [comment]
@Jmolenberghs are you the same person I had the discussion with on the forum?  If so, we can close this issue as that was a password-typo problem, not a problem with the login process.  I have added some error trapping so if this happens again, it will be more polite when it fails.

**Comment by Jmolenberghs** [comment]
@jeff-zucker , I updated my post on the forum.
It was not a typo, but my password ending with an **ampersand**.
After changing my password on the ipd, with the reset procedure it doesn't produce the error.
But when I change it to another password, again ending with an ampersand, the error is back.

![image](https://user-images.githubusercontent.com/37439103/100965857-e6624d80-352b-11eb-88c8-0cc5570bdc66.png)

**Comment by jeff-zucker** [comment]
My apologies, of course, it was not a typo.  I've deleted my comment above.  And I'll look into what I might need to escape on my end.  So the issue will remain open until I find out about that.
